#!/usr/bin/env bash

set -euo pipefail

function usage {
cat >&2 <<EOF
Usage: install-nixos [OPTIONS]

Restore SSH keys from encrypted storage

Options:
  -m, --machine=machine  Name of target machine, required
  -v, --vault=path       Path to host SSH keys, required
  -f, --flake=file       Path to nix installation flake, required
  -h, --help             Show this help
EOF
}

if (( $EUID != 0 )); then
  echo "Please run $0 as root"
  exit 1
fi

# Get CLI options
opts=$(getopt --options "f:m:v:h" --long "flake:,machine:,vault:,help" -- "$@")

# Inspect CLI options
eval set -- "$opts"
while true; do
  case $1 in
    -f|--flake)
      export FLAKE_ROOT=$2
      shift 2
    ;;
    -m|--machine)
      export TARGET_MACHINE=$2
      shift 2
    ;;
    -v|--vault)
      export VAULT_DIR=$2
      shift 2
    ;;
    -h|--help)
      usage
      exit 0
    ;;
    --)
      shift
      break
    ;;
    *)
      echo -e "Unhandled option '$1'"
      exit 2
    ;;
  esac
done

# Sanity check
echo "Install NixOS for host ${TARGET_MACHINE:?} Using nix flake ${FLAKE_ROOT:?} with SSH host key from ${VAULT_DIR:?}/$TARGET_MACHINE.tar.age"
echo
# Start installation
WYVERN_DIR=$(readlink -f $0 | xargs dirname)
nix --experimental-features "nix-command flakes" develop $WYVERN_DIR#run-installer
