#!/usr/bin/env bash

set -euo pipefail

function usage {
cat >&2 <<EOF
Usage: install-nixos [OPTIONS]

Restore SSH keys from encrypted storage

Options:
  -m, --machine=machine  Name of target machine, required
  -h, --help             Show this help
EOF
}

if (( $EUID != 0 )); then
  echo "Please run $0 as root"
  exit 1
fi

WYVERN_DIR=$(readlink -f $0 | xargs dirname)
export VAULT_DIR=$WYVERN_DIR/vault
export TEMPLATE_DIR=$WYVERN_DIR/templates

# Get CLI options
opts=$(getopt --options "f:m:h" --long "flake:,machine:,help" -- "$@")

# Inspect CLI options
eval set -- "$opts"
while true; do
  case $1 in
    -m|--machine)
      export TARGET_MACHINE=$2
      shift 2
    ;;
    -h|--help)
      usage
      exit 0
    ;;
    --)
      shift
      break
    ;;
    *)
      echo -e "Unhandled option '$1'"
      exit 2
    ;;
  esac
done

# Sanity check
echo "Install NixOS for host ${TARGET_MACHINE:?} with SSH host key from ${VAULT_DIR:?}/$TARGET_MACHINE.tar.age"
echo
# Start installation
nix --experimental-features "nix-command flakes" develop $WYVERN_DIR#run-installer
